int main(void) {
    mkdir(ROOT,0700);
    FILE* book=fopen("book.txt","wb"); assert(book);
    for(unsigned i=0;i<20000;++i) fputs("这是长篇阅读器的测试段落，检查分页和缓存。\n",book);
    fclose(book);
    NotificationApp n={.settings={.display_brightness=0.7f}};
    Reader r={.notification=&n};
    r.book=storage_file_alloc(NULL); r.index=storage_file_alloc(NULL);
    assert(storage_file_open(r.book,"book.txt",FSAM_READ,FSOM_OPEN_EXISTING));
    r.size=storage_file_size(r.book);
    uint32_t target;
    assert(prepare_index(&r,"book.txt",0,&target,false));
    assert(target==0 && r.pages>10000);
    uint32_t wanted=r.pages/2, offset;
    assert(index_offset(&r,wanted,&offset));
    storage_file_close(r.index);
    book_bytes=0; writes=0;
    assert(prepare_index(&r,"book.txt",offset,&target,false));
    assert(target==wanted && writes==0 && book_bytes==12288);
    printf("PASS: cached reopen read %zu book bytes, zero index writes, restored page %u\n",book_bytes,target);
    storage_file_close(r.index);
    assert(prepare_index(&r,"book.txt",r.size-1,&target,false) && target==r.pages-1);
    storage_file_close(r.index);
    assert(truncate("book.txt.nridx",25)==0);
    writes=0; assert(prepare_index(&r,"book.txt",0,&target,false) && writes>0);
    storage_file_close(r.index);
    cancel_now=true; assert(!prepare_index(&r,"book.txt",0,&target,true));
    storage_file_close(r.index);
    writes=0; assert(prepare_index(&r,"book.txt",offset,&target,false) && writes>0);
    storage_file_close(r.index);
    storage_file_close(r.book);
    book=fopen("book.txt","r+b"); fputc('X',book); fclose(book);
    assert(storage_file_open(r.book,"book.txt",FSAM_READ,FSOM_OPEN_EXISTING));
    writes=0; assert(prepare_index(&r,"book.txt",0,&target,false) && writes>0);
    puts("PASS: truncated cache, cancelled build, changed sampled content rebuild automatically");
    r.light_mode=1; light_apply(&r); assert(n.locks==1);
    light_apply(&r); assert(n.locks==1);
    r.light_mode=2; light_apply(&r); assert(n.locks==0 && n.settings.display_brightness==0);
    notification_message_block(&n,&sequence_display_backlight_on); assert(n.effective==0);
    light_restore(&r); assert(n.settings.display_brightness==0.7f && n.locks==0);
    r.light_mode=2; light_apply(&r);
    r.light_mode=0; light_apply(&r); assert(n.settings.display_brightness==0.7f && n.locks==0);
    r.light_mode=1; light_apply(&r); light_restore(&r); light_restore(&r); assert(n.locks==0);
    r.light_mode=2; r.invert=true; assert(preferences(&r,true));
    r.light_mode=0; r.invert=false; assert(preferences(&r,false));
    assert(r.light_mode==2 && r.invert);
    puts("PASS: light transitions, simulated key wake stays dark, restore, lock balance, persisted settings");
    storage_file_close(r.book); storage_file_close(r.index);
    storage_file_free(r.book); storage_file_free(r.index);
    return 0;
}
